login: &login
  adapter: mysql2
  host: localhost
  username: adminNgVP7dQ
  password: UJWiSRlrTLmB


development:
  database: publify_dev
  <<: *login

test:
  database: publify_tests
  <<: *login

production:
  database: publify
  <<: *login
